export const availableBanknotes = [
  'China',
  'Kazakhstan',
  'Ukraine',
  'Egypt',
  'Turkey',
  'Germany',
  'Poland',
  'Belarus',
  'Slovenia',
  'Moldova',
  'Greece',
  'Uzbekistan',
  'Kyrgyzstan',
  'Azerbaijan',
  'Cyprus',
  'Afghanistan',
  'Dominican Rep.',
  'Vietnam',
  'United Arab Emirates',
  'Thailand',
  'Congo',
  'Hungary',
  'Malaysia',
  'Nigeria',
  'Qatar',
  'Lebanon',
  'Zambia',
  'North Korea',
  'Australia',
  'United Kingdom',
  'Cuba',
  'Madagascar',
  'Nepal',
  'Bangladesh',
  'Indonesia',
  'United States of America',
  'Armenia',
  'Croatia',
  'Tajikistan',
  'Brazil',
  'Turkmenistan',
  'Iran',
  'India',
  'Honduras',
  'Venezuela',
  'Laos',
  'Estonia',
  'Cambodia',
  'Serbia',
  'Libya',
  'Sri Lanka',
  'Pakistan',
  'Syria',
  'South Africa',
  'Bulgaria',
  'Burundi',
  'Russia',
  'Georgia',
  'Argentina',
]